/* Create tables */
PRINT 'Create tables'
GO

CREATE TABLE PEOPLE(
	[PERSON_ID] INT NOT NULL IDENTITY,
	[FIRST_NAME] VARCHAR(MAX) NULL,
	[LAST_NAME] VARCHAR(MAX) NULL,
	[DATE_OF_BIRTH] DATETIME NULL
)

CREATE TABLE PHOTOS(
	[PHOTO_ID] INT NOT NULL IDENTITY,
	[FILENAME] VARCHAR(MAX) NULL,
	[DATA] VARBINARY(MAX) NULL
)

/* Primary keys */
PRINT 'Create primary keys'
GO

ALTER TABLE [PEOPLE] ADD CONSTRAINT PK_VEHICLE PRIMARY KEY ([PERSON_ID])
GO

ALTER TABLE [PHOTOS] ADD CONSTRAINT PK_VEHICLE PRIMARY KEY ([PHOTO_ID])
GO